<?php

namespace RedSolidaria\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonaFisicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonaFisicaRepository extends EntityRepository
{
}
