<?php

namespace RedSolidaria\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * PublicacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicacionRepository extends EntityRepository {
    
    /*
     * devuelve las ultimas 5 publicaciones creadas
     */
    public function ultimasPublicaciones(){
        
        return $this->getEntityManager()
                    ->createQuery('SELECT p.titulo FROM RedSolidariaMainBundle:Publicacion p ORDER BY p.id DESC')
                    ->setMaxResults(5)
                    ->getResult();
    }
}
